<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [1]:</p>
<p>In [2]:</p>
<p>In [3]:</p>
<p>In [4]:</p></th>
<th><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>importpandasaspd</strong><br />
<strong>importnumpyasnp</strong><br />
<strong>importmatplotlib.pyplotasplt</strong><br />
<strong>importseabornassns</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df = pd.read_csv('train_mercdz.csv')</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>test_df = pd.read_csv('test_mercdz.csv')</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.head()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

| Out\[4\]: |       | **ID** | **y**  | **X0** | **X1** | **X2** | **X3** | **X4** | **X5** | **X6** | **X8** | **...** | **X375** | **X376** | **X377** | **X378** | **X379** | **X380** | **X382** | **X383** | **X384** | **X385** |
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|           | **0** | 0      | 130.81 | k      | v      | at     | a      | d      | u      | j      | o      | ...     | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **1** | 6      | 88.53  | k      | t      | av     | e      | d      | y      | l      | o      | ...     | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **2** | 7      | 76.26  | az     | w      | n      | c      | d      | x      | j      | x      | ...     | 0        | 0        | 0        | 0        | 0        | 0        | 1        | 0        | 0        | 0        |
|           | **3** | 9      | 80.62  | az     | t      | n      | f      | d      | x      | l      | e      | ...     | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **4** | 13     | 78.02  | az     | v      | n      | f      | d      | h      | d      | n      | ...     | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>In [5]:</th>
<th><blockquote>
<p>5 rows × 378 columns</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>test_df.head()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

| Out\[5\]: |       | **ID** | **X0** | **X1** | **X2** | **X3** | **X4** | **X5** | **X6** | **X8** | **X10** | **...** | **X375** | **X376** | **X377** | **X378** | **X379** | **X380** | **X382** | **X383** | **X384** | **X385** |
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|           | **0** | 1      | az     | v      | n      | f      | d      | t      | a      | w      | 0       | ...     | 0        | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **1** | 2      | t      | b      | ai     | a      | d      | b      | g      | y      | 0       | ...     | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **2** | 3      | az     | v      | as     | f      | d      | a      | j      | j      | 0       | ...     | 0        | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **3** | 4      | az     | l      | n      | f      | d      | z      | l      | n      | 0       | ...     | 0        | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        |
|           | **4** | 5      | w      | s      | as     | c      | d      | y      | i      | m      | 0       | ...     | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>In [6]:</th>
<th><blockquote>
<p>5 rows × 377 columns</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.shape, test_df.shape</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[6]: ((4209, 378), (4209, 377))</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [7]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.dtypes, test_df.dtypes</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>Out[7]: (ID int64</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> y float64  
> X0 object  
> X1 object  
> X2 object  
> ...
>
> X380 int64  
> X382 int64  
> X383 int64  
> X384 int64  
> X385 int64  
> Length: 378, dtype: object,  
> ID int64  
> X0 object  
> X1 object  
> X2 object  
> X3 object  
> ...
>
> X380 int64  
> X382 int64  
> X383 int64  
> X384 int64  
> X385 int64

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>In [8]:</th>
<th><blockquote>
<p>Length: 377, dtype: object)</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.var(), test_df.var()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>Out[8]: (ID 5.941936e+06</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> y 1.607667e+02  
> X10 1.313092e-02  
> X11 0.000000e+00  
> X12 6.945713e-02  
> ...
>
> X380 8.014579e-03  
> X382 7.546747e-03  
> X383 1.660732e-03  
> X384 4.750593e-04  
> X385 1.423823e-03  
> Length: 370, dtype: float64,  
> ID 5.871311e+06  
> X10 1.865006e-02  
> X11 2.375861e-04  
> X12 6.885074e-02  
> X13 5.734498e-02  
> ...
>
> X380 8.014579e-03  
> X382 8.715481e-03  
> X383 4.750593e-04  
> X384 7.124196e-04  
> X385 1.660732e-03

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>In [9]:</th>
<th><blockquote>
<p>Length: 369, dtype: float64)</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.columns, test_df.columns</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>Out[9]: (Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6',
'X8',</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

...

> 'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383',
> 'X384',  
> 'X385'\],  
> dtype='object', length=378),  
> Index(\['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',  
> ...
>
> 'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383',
> 'X384',  
> 'X385'\],

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [10]:</p>
<p>In [11]:</p></th>
<th><blockquote>
<p>dtype='object', length=377))</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em>## checked for null value in train data and test data</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.isnull().sum().sum(), test_df.isnull().sum().sum()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[11]: (0, 0)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [12]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>dtype_data=train_df.dtypes.reset_index()<br />
dtype_data.columns = ["Count", "Column Type"]<br />
dtype_data.groupby("Column Type").aggregate('count').reset_index()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 25%" />
<col style="width: 25%" />
<col style="width: 25%" />
<col style="width: 25%" />
</colgroup>
<thead>
<tr class="header">
<th>Out[12]:</th>
<th colspan="2"><strong>Column Type</strong></th>
<th><blockquote>
<p><strong>Count</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>0</strong></td>
<td>int64</td>
<td><blockquote>
<p>369</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>1</strong></td>
<td>float64</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td rowspan="2"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>2</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
<td rowspan="2">object</td>
<td rowspan="2"><blockquote>
<p>8</p>
</blockquote></td>
</tr>
<tr class="even">
<td rowspan="2">In [13]:</td>
</tr>
<tr class="odd">
<td colspan="3"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>dtype_data=test_df.dtypes.reset_index()<br />
dtype_data.columns = ["Count", "Column Type"]<br />
dtype_data.groupby("Column Type").aggregate('count').reset_index()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 25%" />
<col style="width: 25%" />
<col style="width: 25%" />
<col style="width: 25%" />
</colgroup>
<thead>
<tr class="header">
<th>Out[13]:</th>
<th colspan="2"><strong>Column Type</strong></th>
<th><blockquote>
<p><strong>Count</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>0</strong></td>
<td>int64</td>
<td><blockquote>
<p>369</p>
</blockquote></td>
</tr>
<tr class="even">
<td rowspan="2"><p>In [14]:</p>
<p>In [15]:</p></td>
<td><strong>1</strong></td>
<td>object</td>
<td><blockquote>
<p>8</p>
</blockquote></td>
</tr>
<tr class="odd">
<td colspan="3"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em># since majority of the columns are integers with 8 categorical
columns and 1 float column</em> <em>(target variable) in train
data</em><br />
<em># in test data 8 categorical columns</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.iloc[:15,:15]</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table style="width:100%;">
<colgroup>
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
</colgroup>
<thead>
<tr class="header">
<th>Out[15]:</th>
<th colspan="2"><strong>ID</strong></th>
<th><strong>y</strong></th>
<th colspan="3"><strong>X0</strong></th>
<th colspan="2"><strong>X1</strong></th>
<th><strong>X2</strong></th>
<th><strong>X3</strong></th>
<th><strong>X4</strong></th>
<th><strong>X5</strong></th>
<th colspan="3"><strong>X6</strong></th>
<th colspan="2"><strong>X8</strong></th>
<th><strong>X10</strong></th>
<th><strong>X11</strong></th>
<th><strong>X12</strong></th>
<th><strong>X13</strong></th>
<th><blockquote>
<p><strong>X14</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>0</strong></td>
<td>0</td>
<td colspan="2">130.81</td>
<td colspan="3">k</td>
<td>v</td>
<td>at</td>
<td>a</td>
<td>d</td>
<td colspan="3">u</td>
<td colspan="2">j</td>
<td>o</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>1</strong></td>
<td>6</td>
<td colspan="2">88.53</td>
<td colspan="3">k</td>
<td>t</td>
<td>av</td>
<td>e</td>
<td>d</td>
<td colspan="3">y</td>
<td colspan="2">l</td>
<td>o</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>2</strong></td>
<td>7</td>
<td>76.26</td>
<td colspan="4">az</td>
<td>w</td>
<td>n</td>
<td>c</td>
<td>d</td>
<td colspan="3">x</td>
<td colspan="2">j</td>
<td>x</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>3</strong></td>
<td>9</td>
<td>80.62</td>
<td colspan="4">az</td>
<td>t</td>
<td>n</td>
<td>f</td>
<td>d</td>
<td colspan="3">x</td>
<td colspan="2">l</td>
<td>e</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>4</strong></td>
<td>13</td>
<td>78.02</td>
<td colspan="4">az</td>
<td>v</td>
<td>n</td>
<td>f</td>
<td>d</td>
<td colspan="2">h</td>
<td colspan="3">d</td>
<td>n</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>5</strong></td>
<td>18</td>
<td colspan="2">92.93</td>
<td colspan="3">t</td>
<td>b</td>
<td>e</td>
<td>c</td>
<td>d</td>
<td colspan="2">g</td>
<td colspan="3">h</td>
<td>s</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>6</strong></td>
<td>24</td>
<td>128.76</td>
<td colspan="4">al</td>
<td>r</td>
<td>e</td>
<td>f</td>
<td>d</td>
<td colspan="2">f</td>
<td colspan="3">h</td>
<td>s</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>7</strong></td>
<td>25</td>
<td colspan="2">91.91</td>
<td colspan="3">o</td>
<td>l</td>
<td>as</td>
<td>f</td>
<td>d</td>
<td colspan="3">f</td>
<td colspan="2">j</td>
<td>a</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>8</strong></td>
<td>27</td>
<td>108.67</td>
<td colspan="4">w</td>
<td>s</td>
<td>as</td>
<td>e</td>
<td>d</td>
<td colspan="3">f</td>
<td colspan="2">i</td>
<td>h</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>9</strong></td>
<td>30</td>
<td colspan="3"><blockquote>
<p>126.99</p>
</blockquote></td>
<td colspan="2">j</td>
<td>b</td>
<td>aq</td>
<td>c</td>
<td>d</td>
<td colspan="2">f</td>
<td colspan="3">a</td>
<td>e</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>10</strong></td>
<td>31</td>
<td colspan="2">102.09</td>
<td colspan="3">h</td>
<td>r</td>
<td>r</td>
<td>f</td>
<td>d</td>
<td colspan="2">f</td>
<td colspan="3">h</td>
<td>p</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>11</strong></td>
<td>32</td>
<td>98.12</td>
<td colspan="4">al</td>
<td>r</td>
<td>e</td>
<td>f</td>
<td>d</td>
<td colspan="2">f</td>
<td colspan="3">h</td>
<td>o</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>12</strong></td>
<td>34</td>
<td colspan="2">82.62</td>
<td colspan="3">s</td>
<td>b</td>
<td>ai</td>
<td>c</td>
<td>d</td>
<td colspan="2">f</td>
<td colspan="2">g</td>
<td colspan="2">m</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>13</strong></td>
<td>36</td>
<td>94.12</td>
<td colspan="4">al</td>
<td>r</td>
<td>e</td>
<td>f</td>
<td>d</td>
<td colspan="2">j</td>
<td colspan="3">h</td>
<td>o</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td rowspan="2"><strong>14</strong></td>
<td rowspan="2">37</td>
<td colspan="2" rowspan="2"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th>99.15</th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
<td colspan="3" rowspan="2">o</td>
<td rowspan="2">s</td>
<td rowspan="2">as</td>
<td rowspan="2">e</td>
<td rowspan="2">d</td>
<td colspan="2" rowspan="2">j</td>
<td colspan="2" rowspan="2">g</td>
<td colspan="2" rowspan="2">m</td>
<td rowspan="2">0</td>
<td rowspan="2">0</td>
<td rowspan="2">0</td>
<td rowspan="2">0</td>
<td rowspan="2"><blockquote>
<p>1</p>
</blockquote></td>
</tr>
<tr class="even">
<td rowspan="2">In [16]:</td>
</tr>
<tr class="odd">
<td colspan="22"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>test_df.iloc[:15,:15]</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table style="width:100%;">
<colgroup>
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
</colgroup>
<thead>
<tr class="header">
<th>Out[16]:</th>
<th colspan="2"><strong>ID</strong></th>
<th><strong>X0</strong></th>
<th colspan="3"><strong>X1</strong></th>
<th colspan="2"><strong>X2</strong></th>
<th><strong>X3</strong></th>
<th><strong>X4</strong></th>
<th><strong>X5</strong></th>
<th colspan="3"><strong>X6</strong></th>
<th colspan="2"><strong>X8</strong></th>
<th><strong>X10</strong></th>
<th><strong>X11</strong></th>
<th><strong>X12</strong></th>
<th><strong>X13</strong></th>
<th><strong>X14</strong></th>
<th><blockquote>
<p><strong>X15</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>0</strong></td>
<td>1</td>
<td colspan="2">az</td>
<td colspan="3">v</td>
<td>n</td>
<td>f</td>
<td>d</td>
<td colspan="2">t</td>
<td colspan="3">a</td>
<td>w</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>1</strong></td>
<td>2</td>
<td colspan="2">t</td>
<td colspan="2">b</td>
<td colspan="2">ai</td>
<td>a</td>
<td>d</td>
<td colspan="2">b</td>
<td colspan="3">g</td>
<td>y</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>2</strong></td>
<td>3</td>
<td colspan="2">az</td>
<td colspan="2">v</td>
<td colspan="2">as</td>
<td>f</td>
<td>d</td>
<td colspan="3">a</td>
<td colspan="2">j</td>
<td>j</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>3</strong></td>
<td>4</td>
<td colspan="3"><blockquote>
<p>az</p>
</blockquote></td>
<td colspan="2">l</td>
<td>n</td>
<td>f</td>
<td>d</td>
<td colspan="3">z</td>
<td colspan="2">l</td>
<td>n</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>4</strong></td>
<td>5</td>
<td colspan="2">w</td>
<td colspan="2">s</td>
<td colspan="2">as</td>
<td>c</td>
<td>d</td>
<td colspan="3">y</td>
<td>i</td>
<td colspan="2">m</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>5</strong></td>
<td>8</td>
<td>y</td>
<td colspan="4">aa</td>
<td>ai</td>
<td>e</td>
<td>d</td>
<td colspan="2">x</td>
<td colspan="3">g</td>
<td>s</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>6</strong></td>
<td>10</td>
<td colspan="2">x</td>
<td colspan="2">b</td>
<td colspan="2">ae</td>
<td>d</td>
<td>d</td>
<td colspan="2">x</td>
<td colspan="3">d</td>
<td>y</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>7</strong></td>
<td>11</td>
<td colspan="2">f</td>
<td colspan="3">s</td>
<td>ae</td>
<td>c</td>
<td>d</td>
<td colspan="2">h</td>
<td colspan="3">d</td>
<td>a</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>8</strong></td>
<td>12</td>
<td colspan="3"><blockquote>
<p>ap</p>
</blockquote></td>
<td colspan="2">l</td>
<td>s</td>
<td>c</td>
<td>d</td>
<td colspan="3">h</td>
<td colspan="2">j</td>
<td>n</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>9</strong></td>
<td>14</td>
<td colspan="2">o</td>
<td colspan="2">v</td>
<td colspan="2">as</td>
<td>f</td>
<td>d</td>
<td colspan="2">g</td>
<td colspan="3">f</td>
<td>v</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>10</strong></td>
<td>15</td>
<td colspan="3"><blockquote>
<p>ap</p>
</blockquote></td>
<td colspan="2">l</td>
<td>s</td>
<td>c</td>
<td>d</td>
<td colspan="2">g</td>
<td colspan="3">d</td>
<td>n</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>11</strong></td>
<td>16</td>
<td colspan="2">ay</td>
<td colspan="3">b</td>
<td>b</td>
<td>a</td>
<td>d</td>
<td colspan="3">g</td>
<td colspan="2">l</td>
<td>r</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td><strong>12</strong></td>
<td>17</td>
<td colspan="2">al</td>
<td colspan="3">r</td>
<td>e</td>
<td>f</td>
<td>d</td>
<td colspan="2">g</td>
<td colspan="3">h</td>
<td>o</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td></td>
<td><strong>13</strong></td>
<td>19</td>
<td colspan="2">o</td>
<td colspan="2">v</td>
<td colspan="2">ae</td>
<td>g</td>
<td>d</td>
<td colspan="2">g</td>
<td colspan="3">g</td>
<td>j</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="odd">
<td></td>
<td rowspan="2"><strong>14</strong></td>
<td rowspan="2">20</td>
<td colspan="2" rowspan="2">h</td>
<td colspan="2" rowspan="2">a</td>
<td colspan="2" rowspan="2">ak</td>
<td rowspan="2">f</td>
<td rowspan="2">d</td>
<td colspan="3" rowspan="2"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th>g</th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
<td colspan="2" rowspan="2">l</td>
<td rowspan="2">t</td>
<td rowspan="2">0</td>
<td rowspan="2">0</td>
<td rowspan="2">1</td>
<td rowspan="2">0</td>
<td rowspan="2">0</td>
<td rowspan="2"><blockquote>
<p>0</p>
</blockquote></td>
</tr>
<tr class="even">
<td rowspan="2"><p>In [17]:</p>
<p>In [18]:</p></td>
</tr>
<tr class="odd">
<td colspan="22"><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em># checked for the unique value</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>obj_dtype = train_df.dtypes[train_df.dtypes=='object'].index
<strong>for</strong> i <strong>in</strong> obj_dtype:<br />
print(i, train_df[i].unique())</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X0 ['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj'
'ak' 'am'</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as'
> 'i'  
> 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab'\]  
> X1 \['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u'
> 'p' 'n'  
> 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab'\]  
> X2 \['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's'
> 'f' 'd'  
> 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't'
> 'an'  
> 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar'\]  
> X3 \['a' 'e' 'c' 'f' 'd' 'b' 'g'\]  
> X4 \['d' 'b' 'c' 'a'\]  
> X5 \['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac' 'ad'
> 'ae'  
> 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa'\]  
> X6 \['j' 'l' 'd' 'h' 'i' 'a' 'g' 'c' 'k' 'e' 'f' 'b'\]  
> X8 \['o' 'x' 'e' 'n' 's' 'a' 'h' 'p' 'm' 'k' 'd' 'i' 'v' 'j' 'b' 'q'
> 'w' 'g'

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>In [19]:</th>
<th><blockquote>
<p>'y' 'l' 'f' 'u' 'r' 't' 'c']</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>obj_dtype = test_df.dtypes[test_df.dtypes=='object'].index
<strong>for</strong> i <strong>in</strong> obj_dtype:<br />
print(i, test_df[i].unique())</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X0 ['az' 't' 'w' 'y' 'x' 'f' 'ap' 'o' 'ay' 'al' 'h' 'z' 'aj' 'd' 'v'
'ak'</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> 'ba' 'n' 'j' 's' 'af' 'ax' 'at' 'aq' 'av' 'm' 'k' 'a' 'e' 'ai' 'i'
> 'ag'  
> 'b' 'am' 'aw' 'as' 'r' 'ao' 'u' 'l' 'c' 'ad' 'au' 'bc' 'g' 'an' 'ae'
> 'p'  
> 'bb'\]  
> X1 \['v' 'b' 'l' 's' 'aa' 'r' 'a' 'i' 'p' 'c' 'o' 'm' 'z' 'e' 'h' 'w'
> 'g' 'k'  
> 'y' 't' 'u' 'd' 'j' 'q' 'n' 'f' 'ab'\]  
> X2 \['n' 'ai' 'as' 'ae' 's' 'b' 'e' 'ak' 'm' 'a' 'aq' 'ag' 'r' 'k'
> 'aj' 'ay'  
> 'ao' 'an' 'ac' 'af' 'ax' 'h' 'i' 'f' 'ap' 'p' 'au' 't' 'z' 'y' 'aw'
> 'd'  
> 'at' 'g' 'am' 'j' 'x' 'ab' 'w' 'q' 'ah' 'ad' 'al' 'av' 'u'\]  
> X3 \['f' 'a' 'c' 'e' 'd' 'g' 'b'\]  
> X4 \['d' 'b' 'a' 'c'\]  
> X5 \['t' 'b' 'a' 'z' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag'
> 'ab' 'ac'  
> 'ad' 'ae' 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa'\]  
> X6 \['a' 'g' 'j' 'l' 'i' 'd' 'f' 'h' 'c' 'k' 'e' 'b'\]  
> X8 \['w' 'y' 'j' 'n' 'm' 's' 'a' 'v' 'r' 'o' 't' 'h' 'c' 'k' 'p' 'u'
> 'd' 'g'

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [20]:</p>
<p>In [21]:</p>
<p>In [22]:</p>
<p>In [23]:</p>
<p>In [24]:</p>
<p>In [25]:</p>
<p>In [26]:</p>
<p>In [27]:</p>
<p>In [28]:</p>
<p>In [29]:</p>
<p>In [30]:</p>
<p>In [31]:</p>
<p>In [32]:</p>
<p>In [33]:</p></th>
<th><blockquote>
<p>'b' 'q' 'e' 'l' 'f' 'i' 'x']</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em>#Encoding the catagorical value</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>cat_columns = ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>fromsklearn.preprocessingimport</strong> LabelEncoder<br />
le = LabelEncoder()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le0 = LabelEncoder()<br />
le0.fit(list(train_df.X0)+list(test_df.X0))<br />
train_df.X0 = le0.transform(train_df.X0)<br />
test_df.X0 = le0.transform(test_df.X0)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le1 = LabelEncoder()<br />
le1.fit(list(train_df.X1)+list(test_df.X1))<br />
train_df.X1 = le1.transform(train_df.X1)<br />
test_df.X1 = le1.transform(test_df.X1)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le2 = LabelEncoder()<br />
le2.fit(list(train_df.X2)+list(test_df.X2))<br />
train_df.X2 = le2.transform(train_df.X2)<br />
test_df.X2 = le2.transform(test_df.X2)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le3 = LabelEncoder()<br />
le3.fit(list(train_df.X3)+list(test_df.X3))<br />
train_df.X3 = le3.transform(train_df.X3)<br />
test_df.X3 = le3.transform(test_df.X3)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le4 = LabelEncoder()<br />
le4.fit(list(train_df.X4)+list(test_df.X4))<br />
train_df.X4 = le4.transform(train_df.X4)<br />
test_df.X4 = le4.transform(test_df.X4)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le5 = LabelEncoder()<br />
le5.fit(list(train_df.X5)+list(test_df.X5))<br />
train_df.X5 = le5.transform(train_df.X5)<br />
test_df.X5 = le5.transform(test_df.X5)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le6 = LabelEncoder()<br />
le6.fit(list(train_df.X6)+list(test_df.X6))<br />
train_df.X6 = le6.transform(train_df.X6)<br />
test_df.X6 = le6.transform(test_df.X6)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le8 = LabelEncoder()<br />
le8.fit(list(train_df.X8)+list(test_df.X8))<br />
train_df.X8 = le8.transform(train_df.X8)<br />
test_df.X8 = le8.transform(test_df.X8)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em>## Encoded the float value of target variable in train
data</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>le9 = LabelEncoder()<br />
train_df['y'] =le9.fit_transform(train_df['y'])</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>train_df.head()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

| Out\[33\]: |       | **ID** | **y** | **X0** | **X1** | **X2** | **X3** | **X4** | **X5** | **X6** | **X8** | **...** | **X375** | **X376** | **X377** | **X378** | **X379** | **X380** | **X382** | **X383** | **X384** | **X385** |
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|            | **0** | 0      | 2466  | 37     | 23     | 20     | 0      | 3      | 27     | 9      | 14     | ...     | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **1** | 6      | 366   | 37     | 21     | 22     | 4      | 3      | 31     | 11     | 14     | ...     | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **2** | 7      | 69    | 24     | 24     | 38     | 2      | 3      | 30     | 9      | 23     | ...     | 0        | 0        | 0        | 0        | 0        | 0        | 1        | 0        | 0        | 0        |
|            | **3** | 9      | 133   | 24     | 21     | 38     | 5      | 3      | 30     | 11     | 4      | ...     | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **4** | 13     | 106   | 24     | 23     | 38     | 5      | 3      | 14     | 3      | 13     | ...     | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>In [34]:</th>
<th><blockquote>
<p>5 rows × 378 columns</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>test_df.head()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

| Out\[34\]: |       | **ID** | **X0** | **X1** | **X2** | **X3** | **X4** | **X5** | **X6** | **X8** | **X10** | **...** | **X375** | **X376** | **X377** | **X378** | **X379** | **X380** | **X382** | **X383** | **X384** | **X385** |
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|            | **0** | 1      | 24     | 23     | 38     | 5      | 3      | 26     | 0      | 22     | 0       | ...     | 0        | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **1** | 2      | 46     | 3      | 9      | 0      | 3      | 9      | 6      | 24     | 0       | ...     | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **2** | 3      | 24     | 23     | 19     | 5      | 3      | 0      | 9      | 9      | 0       | ...     | 0        | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **3** | 4      | 24     | 13     | 38     | 5      | 3      | 32     | 11     | 13     | 0       | ...     | 0        | 0        | 0        | 1        | 0        | 0        | 0        | 0        | 0        | 0        |
|            | **4** | 5      | 49     | 20     | 19     | 2      | 3      | 31     | 8      | 12     | 0       | ...     | 1        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        | 0        |

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [35]:</p>
<p>In [36]:</p></th>
<th><blockquote>
<p>5 rows × 377 columns</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em>## checked for unique value with zero in train data</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>unique_value_dict = {}<br />
<strong>for</strong> col <strong>in</strong> train_df.columns:<br />
<strong>if</strong> col <strong>notin</strong> ["ID", "y", "X0", "X1",
"X2", "X3", "X4", "X5", "X6", "X8"]: unique_value
=str(np.sort(train_df[col].unique()).tolist())<br />
t_list = unique_value_dict.get(unique_value, [])<br />
t_list.append(col)<br />
unique_value_dict[unique_value] = t_list[:]<br />
<strong>for</strong> unique_val, columns <strong>in</strong>
unique_value_dict.items():<br />
print("Columns containing the unique values : ",unique_val)<br />
print(columns)<br />
print("-----------------------------------------------------------")</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>Columns containing the unique values : [0, 1]</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> \['X10', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19',
> 'X20', 'X21', 'X22', 'X23', 'X24', 'X26', 'X27', 'X28', 'X29', 'X30',
> 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X 38', 'X39', 'X40',
> 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50',
> 'X5 1', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60',
> 'X61', 'X62', 'X63', 'X6 4', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70',
> 'X71', 'X73', 'X74', 'X75', 'X76', 'X77', 'X7 8', 'X79', 'X80', 'X81',
> 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X9 1',
> 'X92', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101',
> 'X102', 'X103', 'X104', 'X105', 'X106', 'X108', 'X109', 'X110',
> 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X11 7', 'X118',
> 'X119', 'X120', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127',
> 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135',
> 'X136', 'X137', 'X138', 'X139', 'X140', 'X14 1', 'X142', 'X143',
> 'X144', 'X145', 'X146', 'X147', 'X148', 'X150', 'X151', 'X152',
> 'X153', 'X154', 'X155', 'X156', 'X157', 'X158', 'X159', 'X160',
> 'X161', 'X162', 'X163', 'X164', 'X16 5', 'X166', 'X167', 'X168',
> 'X169', 'X170', 'X171', 'X172', 'X173', 'X174', 'X175', 'X176',
> 'X177', 'X178', 'X179', 'X180', 'X181', 'X182', 'X183', 'X184',
> 'X185', 'X186', 'X187', 'X18 9', 'X190', 'X191', 'X192', 'X194',
> 'X195', 'X196', 'X197', 'X198', 'X199', 'X200', 'X201', 'X202',
> 'X203', 'X204', 'X205', 'X206', 'X207', 'X208', 'X209', 'X210',
> 'X211', 'X212', 'X21 3', 'X214', 'X215', 'X216', 'X217', 'X218',
> 'X219', 'X220', 'X221', 'X222', 'X223', 'X224', 'X225', 'X226',
> 'X227', 'X228', 'X229', 'X230', 'X231', 'X232', 'X234', 'X236',
> 'X237', 'X23 8', 'X239', 'X240', 'X241', 'X242', 'X243', 'X244',
> 'X245', 'X246', 'X247', 'X248', 'X249', 'X250', 'X251', 'X252',
> 'X253', 'X254', 'X255', 'X256', 'X257', 'X258', 'X259', 'X260', 'X26
> 1', 'X262', 'X263', 'X264', 'X265', 'X266', 'X267', 'X269', 'X270',
> 'X271', 'X272', 'X273', 'X274', 'X275', 'X276', 'X277', 'X278',
> 'X279', 'X280', 'X281', 'X282', 'X283', 'X284', 'X28 5', 'X286',
> 'X287', 'X288', 'X291', 'X292', 'X294', 'X295', 'X296', 'X298',
> 'X299', 'X300', 'X301', 'X302', 'X304', 'X305', 'X306', 'X307',
> 'X308', 'X309', 'X310', 'X311', 'X312', 'X31 3', 'X314', 'X315',
> 'X316', 'X317', 'X318', 'X319', 'X320', 'X321', 'X322', 'X323',
> 'X324', 'X325', 'X326', 'X327', 'X328', 'X329', 'X331', 'X332',
> 'X333', 'X334', 'X335', 'X336', 'X33 7', 'X338', 'X339', 'X340',
> 'X341', 'X342', 'X343', 'X344', 'X345', 'X346', 'X348', 'X349',
> 'X350', 'X351', 'X352', 'X353', 'X354', 'X355', 'X356', 'X357',
> 'X358', 'X359', 'X360', 'X36 1', 'X362', 'X363', 'X364', 'X365',
> 'X366', 'X367', 'X368', 'X369', 'X370', 'X371', 'X372', 'X373',
> 'X374', 'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382',
> 'X383', 'X384', 'X38 5'\]  
> -----------------------------------------------------------  
> Columns containing the unique values : \[0\]  
> \['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
> 'X293', 'X297', 'X330', 'X34 7'\]

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [37]:</p>
<p>In [38]:</p>
<p>In [39]:</p></th>
<th><blockquote>
<p>-----------------------------------------------------------</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em># removed the columns with unique values zero and prepared
features and target</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>features = train_df.drop(['y','ID','X11', 'X93', 'X107', 'X233',
'X235', 'X268', 'X289', 'X2 90', 'X293', 'X297', 'X330',
'X347'],axis=1)<br />
target = train_df[['y']]</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>features.shape,target.shape</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[39]: ((4209, 364), (4209, 1))</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [40]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>fromsklearn.model_selectionimport</strong>
train_test_split</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="even">
<td>In [41]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train, X_test, y_train, y_test = train_test_split(features,target,
train_size=.8)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="odd">
<td>In [42]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train.shape,X_test.shape,y_train.shape,y_test.shape</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[42]: ((3367, 364), (842, 364), (3367, 1), (842, 1))</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [43]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em>## perform dimentional reduction</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="even">
<td>In [44]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>fromsklearn.ensembleimport</strong> RandomForestClassifier
my_rf_classifier = RandomForestClassifier()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="odd">
<td>In [45]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>my_rf_classifier.fit(X_train,y_train)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>&lt;ipython-input-45-c44482f685a4&gt;:1: DataConversionWarning: A
column-vector y was passed when a</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>1d array was expected. Please change the shape of y to (n_samples,),
for example using ravel</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>().</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>my_rf_classifier.fit(X_train,y_train)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[45]: RandomForestClassifier()</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [46]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>my_rf_preds = my_rf_classifier.predict(X_test)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="even">
<td>In [47]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>fromsklearn.decompositionimport</strong> PCA</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="odd">
<td>In [48]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>pca = PCA(n_components=.9)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="even">
<td>In [49]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>pca.fit(X_train)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[49]: PCA(n_components=0.9)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [50]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>pca.explained_variance_ratio_</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[50]: array([0.40649473, 0.22023184, 0.13127402, 0.1060638 ,
0.08266735])</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [51]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train_pca = pca.transform(X_train)<br />
X_test_pca = pca.transform(X_test)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="even">
<td>In [52]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train_pca.shape, X_test_pca.shape</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[52]: ((3367, 5), (842, 5))</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [53]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train_pca</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>Out[53]: array([[-21.21943008, -9.21814904, -9.30480999,
-3.68538107,</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> 4.70324379\],  
> \[-12.22347412, 1.71574428, 3.98774322, 11.14641567,  
> -0.63722698\],  
> \[ 25.17616276, -6.56538012, -2.91848216, 4.87629802,  
> -7.39070466\],  
> ...,  
> \[ -4.37292657, 0.57541661, -5.38494447, 12.49000034,  
> -8.09982517\],  
> \[-19.2541749 , 2.64066502, -2.32137973, -5.62146032,  
> 2.17367005\],  
> \[ -0.64241582, 17.75598707, -0.27717285, 10.28449227,

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [54]:</p>
<p>In [55]:</p>
<p>In [56]:</p></th>
<th><blockquote>
<p>-2.06703049]])</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><em># using the same train_df data target to predict in the test_df
data # drop the columns which we have drop in the train_df data</em></p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>features_test = test_df.drop(['ID','X11', 'X93', 'X107', 'X233',
'X235', 'X268', 'X289', 'X2 90', 'X293', 'X297', 'X330',
'X347'],axis=1)<br />
target_test = train_df[['y']]</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>features_test.dtypes</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>Out[56]: X0 int32</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> X1 int32  
> X2 int32  
> X3 int32  
> X4 int32  
> ...
>
> X380 int64  
> X382 int64  
> X383 int64  
> X384 int64  
> X385 int64

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [57]:</p>
<p>In [58]:</p>
<p>In [59]:</p></th>
<th><blockquote>
<p>Length: 364, dtype: object</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>fromsklearn.model_selectionimport</strong>
train_test_split</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train, X_test, y_train, y_test =
train_test_split(features_test,target_test, train_size=.8 )</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>X_train.shape,X_test.shape,y_train.shape,y_test.shape</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th colspan="2"><blockquote>
<p>Out[59]: ((3367, 364), (842, 364), (3367, 1), (842, 1))</p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In [60]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>fromxgboostimport</strong> XGBClassifier, XGBRFClassifier</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="even">
<td>In [61]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>my_xgb_clf = XGBRFClassifier(booster ='gbtree')</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
<tr class="odd">
<td>In [62]:</td>
<td><table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>my_xgb_clf.fit(X_train, y_train)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table></td>
</tr>
</tbody>
</table>

| C:\Users\jsanb\anaconda4\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of l |
|------------------------------------------------------------------------|

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>abel encoder in XGBClassifier is deprecated and will be removed in a
future release. To remov</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>e this warning, do the following: 1) Pass option
use_label_encoder=False when constructing XG</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>BClassifier object; and 2) Encode your labels (y) as integers
starting with 0, i.e. 0, 1, 2,</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>..., [num_class - 1].</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>warnings.warn(label_encoder_deprecation_msg, UserWarning)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>C:\Users\jsanb\anaconda4\lib\site-packages\sklearn\utils\validation.py:63:
DataConversionWarn</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>ing: A column-vector y was passed when a 1d array was expected.
Please change the shape of y</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>to (n_samples, ), for example using ravel().</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>return f(*args, **kwargs)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

> \[13:15:29\] WARNING:
> C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.
> cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used
> with the objective 'mu lti:softprob' was changed from 'merror' to
> 'mlogloss'. Explicitly set eval_metric if you'd li ke to restore the
> old behavior.
>
> Out\[62\]: XGBRFClassifier(base_score=0.5, booster='gbtree',
> colsample_bylevel=1,  
> colsample_bytree=1, enable_categorical=False, gamma=0,  
> gpu_id=-1, importance_type=None, interaction_constraints='',
> max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
> monotone_constraints='()', n_estimators=100, n_jobs=4,  
> num_parallel_tree=100, objective='multi:softprob',  
> predictor='auto', random_state=0, reg_alpha=0,  
> scale_pos_weight=None, tree_method='exact',

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><p>In [63]:</p>
<p>In [ ]:</p></th>
<th><blockquote>
<p>validate_parameters=1, verbosity=None)</p>
</blockquote>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><blockquote>
<p>my_xgb_preds = my_xgb_clf.predict(X_test)</p>
</blockquote></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<tbody>
</tbody>
</table></th>
</tr>
</thead>
<tbody>
</tbody>
</table>